services:
  azurite:
    image: 'mcr.microsoft.com/azure-storage/azurite:latest'
    ports:
      - '10000'
      - '10001'
      - '10002'
  sqlserver:
    image: 'mcr.microsoft.com/mssql/server:latest'
    environment:
      - 'ACCEPT_EULA=yes'
      - 'MSSQL_PID=express'
      - 'MSSQL_SA_PASSWORD=verYs3cret'
    ports:
      - '1433'
